pipeline {
    agent  { label 'slave_1' }
     parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'Branch del progetto git')
        string(name: 'GIT_URL', defaultValue: '', description: 'Url del progetto git')
        string(name: 'ARTIFACT', defaultValue: '', description: 'ArtifactId del progetto git')
        string(name: 'VERSION', defaultValue: '', description: 'Versione del progetto')
    }

    stages {
        stage('Build') {
            steps {
            	echo 'io non saluto'
                echo 'branch.name = develop'
                echo 'projectVersion = 0.0.1-SNAPSHOT'
                echo 'links.scm = ssh://git@git.gbm.lan:8443/nrdv/rdv-vue-app-contatti.git'
            }
        }
    }
}
